-- Run this once in GoDaddy cPanel → phpMyAdmin
-- Select your database first, then paste into the SQL tab

CREATE TABLE IF NOT EXISTS `artists` (
  `id`                   INT AUTO_INCREMENT PRIMARY KEY,
  `name`                 VARCHAR(255)  NOT NULL,
  `last_release`         VARCHAR(10)   NOT NULL DEFAULT '',
  `next_release`         VARCHAR(20)   NOT NULL DEFAULT '',
  `album_title`          VARCHAR(255)  NOT NULL DEFAULT '',
  `confirmed`            TINYINT(1)    NOT NULL DEFAULT 0,
  `incomplete_collection`TINYINT(1)    NOT NULL DEFAULT 0,
  `notes`                VARCHAR(500)  NOT NULL DEFAULT '',
  `url`                  VARCHAR(500)  NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- If the table already exists, run this migration to add the url column:
-- ALTER TABLE `artists` ADD COLUMN `url` VARCHAR(500) NOT NULL DEFAULT '' AFTER `notes`;

INSERT INTO `artists` (`name`, `last_release`, `next_release`, `album_title`, `confirmed`, `incomplete_collection`, `notes`) VALUES
('Embrace',          '2022', '6/12/2026',  'Avalanche',                                       1, 0, ''),
('Pond',             '2024', '6/19/2026',  'Terrestrials',                                    1, 1, ''),
('The Strokes',      '2020', '6/26/2026',  'Reality Awaits',                                  1, 0, ''),
('Muse',             '2022', '6/26/2026',  'The Wow! Signal',                                 1, 0, ''),
('Panda Bear',       '2025', '7/10/2026',  'A ? of When',                                     1, 1, ''),
('Babe Rainbow',     '2025', '7/17/2026',  'Acid and Honey',                                  1, 0, ''),
('Punch Brothers',   '2022', '7/24/2026',  'The Unsung Adventures of the Punch Brothers',     1, 0, ''),
('Charli XCX',       '2025', '7/24/2026',  'Music, Fashion, Film',                            1, 1, ''),
('Shearwater',       '2022', '7/31/2026',  'The New World',                                   1, 1, ''),
('Weezer',           '2022', '8/21/2026',  'Weezer (Gold Album)',                             1, 0, ''),
('The Bravery',      '2009', '12/31/2026', '',                                                0, 0, ''),
('Gotye',            '2011', '12/31/2026', '',                                                0, 0, ''),
('Delphic',          '2013', '12/31/2026', '',                                                0, 0, ''),
('Dikta',            '2015', '12/31/2026', '',                                                0, 0, ''),
('Biggi Hilmars',    '2017', '12/31/2026', '',                                                0, 0, ''),
('The Shins',        '2017', '12/31/2026', '',                                                0, 0, ''),
('The Magic Numbers','2018', '12/31/2026', '',                                                0, 0, ''),
('The Reign of Kindo','2018','12/31/2026', '',                                                0, 0, ''),
('Copeland',         '2019', '12/31/2026', '',                                                0, 0, ''),
('Keane',            '2019', '12/31/2026', '',                                                0, 0, ''),
('The Leisure Society','2019','12/31/2026','Brave Are the Waves',                             0, 0, ''),
('ISLAND',           '2021', '12/31/2026', '',                                                0, 1, 'also solo EP'),
('Editors',          '2022', '12/31/2026', '',                                                0, 1, ''),
('Typhoon',          '2022', '12/31/2026', 'Underground Complex Vol. 2',                      0, 0, ''),
('Empty Country',    '2023', '12/31/2026', '',                                                0, 0, ''),
('Nicole Miglis',    '2023', '12/31/2026', '',                                                0, 0, ''),
('Local Natives',    '2024', '12/31/2026', '',                                                0, 0, ''),
('DAÐI',             '',     '12/31/2026', '',                                                0, 0, ''),
('Steven Curtis',    '',     '12/31/2026', '',                                                0, 0, ''),
('The Twang',        '2024', '3/1/2027',   '',                                                0, 0, ''),
('Fredrik',          '2012', '',           '',                                                0, 0, 'Released single 12/2020'),
('Jimi Goodwin',     '2014', '',           '',                                                0, 0, ''),
('Black Rivers',     '2015', '',           '',                                                0, 0, ''),
('Brandon Flowers',  '2015', '',           '',                                                0, 0, ''),
('Guy Garvey',       '2015', '',           '',                                                0, 0, ''),
('One eskimO',       '2015', '',           '',                                                0, 0, ''),
('Edward Sharpe',    '2016', '',           '',                                                0, 0, ''),
('Radiohead',        '2016', '',           '',                                                0, 0, ''),
('Ariel Pink',       '2017', '',           '',                                                0, 1, ''),
('Hundred Waters',   '2017', '',           '',                                                0, 0, ''),
('Mark Stoermer',    '2017', '',           '',                                                0, 1, ''),
('Mister Heavenly',  '2017', '',           '',                                                0, 1, ''),
('Anna Meredith',    '2019', '',           '',                                                0, 1, ''),
('Deerhunter',       '2019', '',           '',                                                0, 0, ''),
('Fiona Apple',      '2020', '',           '',                                                0, 0, ''),
('Hjaltalín',        '2020', '',           '',                                                0, 0, ''),
('The Republic Tigers','2020','',          '',                                                0, 0, ''),
('Woodkid',          '2020', '',           '',                                                0, 0, ''),
('Damon Albarn',     '2021', '',           '',                                                0, 1, ''),
('Fyfe Dangerfield', '2021', '',           '',                                                0, 0, ''),
('Grasscut',         '2021', '',           '',                                                0, 0, ''),
('The Killers',      '2021', '',           '',                                                0, 0, ''),
('Low',              '2021', '',           '',                                                0, 1, ''),
('Said the Whale',   '2021', '',           '',                                                0, 0, ''),
('Wilderado',        '2021', '',           '',                                                0, 0, ''),
('Alaskalaska',      '2022', '',           '',                                                0, 0, ''),
('Alt-J',            '2022', '',           '',                                                0, 0, ''),
('Arctic Monkeys',   '2022', '',           '',                                                0, 0, ''),
('Broken Bells',     '2022', '',           '',                                                0, 0, ''),
('Daniel Rossen',    '2022', '',           '',                                                0, 0, ''),
('The Family Crest', '2022', '',           '',                                                0, 1, ''),
('Foals',            '2022', '',           '',                                                0, 0, ''),
('Let''s Eat Grandma','2022','',           '',                                                0, 0, ''),
('Mono Town',        '2022', '',           '',                                                0, 0, ''),
('Phoenix',          '2022', '',           '',                                                0, 0, ''),
('Red Hot Chili Peppers','2022','',        '',                                                0, 0, ''),
('Regina Spektor',   '2022', '',           '',                                                0, 0, ''),
('Sohn',             '2022', '',           '',                                                0, 0, ''),
('Sylvan Esso',      '2022', '',           '',                                                0, 0, ''),
('The 1975',         '2022', '',           '',                                                0, 0, ''),
('The Midnight',     '2022', '',           '',                                                0, 1, ''),
('Tom Chaplin',      '2022', '',           '',                                                0, 0, ''),
('Train',            '2022', '',           '',                                                0, 0, ''),
('Two Door Cinema Club','2022','',         '',                                                0, 0, ''),
('Weyes Blood',      '2022', '',           '',                                                0, 1, ''),
('The Album Leaf',   '2023', '',           '',                                                0, 1, ''),
('Belle & Sebastian','2023', '',           '',                                                0, 0, ''),
('Best Frenz',       '2023', '',           '',                                                0, 0, ''),
('M83',              '2023', '',           '',                                                0, 0, ''),
('Noel Gallagher''s','2023', '',           '',                                                0, 0, ''),
('Owl City',         '2023', '',           '',                                                0, 0, ''),
('Royal Blood',      '2023', '',           '',                                                0, 0, ''),
('Sufjan Stevens',   '2023', '',           '',                                                0, 0, ''),
('The National',     '2023', '',           '',                                                0, 1, ''),
('Wye Oak',          '2023', '',           '',                                                0, 1, ''),
('Yo La Tengo',      '2023', '',           '',                                                0, 0, ''),
('Andrew Bird',      '2024', '',           '',                                                0, 0, ''),
('beabadoobee',      '2024', '',           '',                                                0, 0, ''),
('Caribou',          '2024', '',           '',                                                0, 0, ''),
('Coldplay',         '2024', '',           '',                                                0, 0, ''),
('Crumb',            '2024', '',           '',                                                0, 0, ''),
('The Decemberists', '2024', '',           '',                                                0, 0, ''),
('Everything Everything','2024','',        '',                                                0, 0, ''),
('Gepe',             '2024', '',           '',                                                0, 0, ''),
('Glass Beach',      '2024', '',           '',                                                0, 0, ''),
('Goat Girl',        '2024', '',           '',                                                0, 1, ''),
('Guster',           '2024', '',           '',                                                0, 0, ''),
('Islands',          '2024', '',           '',                                                0, 0, ''),
('Joywave',          '2024', '',           '',                                                0, 0, ''),
('Julia Holter',     '2024', '',           '',                                                0, 0, ''),
('Kishi Bashi',      '2024', '',           '',                                                0, 0, ''),
('Magdalena Bay',    '2024', '',           '',                                                0, 0, ''),
('MGMT',             '2024', '',           '',                                                0, 0, ''),
('The Miserable Rich','2024','',           '',                                                0, 0, ''),
('OneRepublic',      '2024', '',           '',                                                0, 0, ''),
('Outside Air',      '2024', '',           '',                                                0, 0, ''),
('Peach Pit',        '2024', '',           '',                                                0, 0, ''),
('Ryan Hahn',        '2024', '',           '',                                                0, 0, ''),
('Snow Patrol',      '2024', '',           '',                                                0, 0, ''),
('St. Vincent',      '2024', '',           '',                                                0, 0, ''),
('Starsailor',       '2024', '',           '',                                                0, 0, ''),
('Still Corners',    '2024', '',           '',                                                0, 0, ''),
('The Marías',       '2024', '',           '',                                                0, 0, ''),
('The Smile',        '2024', '',           '',                                                0, 0, ''),
('Thirteen Senses',  '2024', '',           '',                                                0, 0, ''),
('Travis',           '2024', '',           '',                                                0, 0, ''),
('Vampire Weekend',  '2024', '',           '',                                                0, 0, ''),
('Why?',             '2024', '',           '',                                                0, 0, ''),
('Wilco',            '2024', '',           '',                                                0, 0, ''),
('Arcade Fire',      '2025', '',           '',                                                0, 0, ''),
('B.C. Camplight',   '2025', '',           '',                                                0, 0, ''),
('bbno$',            '2025', '',           '',                                                0, 0, ''),
('Bon Iver',         '2025', '',           '',                                                0, 0, ''),
('Born Ruffians',    '2025', '',           '',                                                0, 1, ''),
('Captain',          '2025', '',           '',                                                0, 0, ''),
('Clearlake',        '2025', '',           '',                                                0, 0, ''),
('Cleopatrick',      '2025', '',           '',                                                0, 1, ''),
('Darkside',         '2025', '',           '',                                                0, 0, ''),
('Dirty Projectors', '2025', '',           '',                                                0, 1, ''),
('Djo',              '2025', '',           '',                                                0, 1, ''),
('Doves',            '2025', '',           '',                                                0, 0, ''),
('Elbow',            '2025', '',           '',                                                0, 0, ''),
('Emancipator',      '2025', '',           '',                                                0, 0, ''),
('Franz Ferdinand',  '2025', '',           '',                                                0, 0, ''),
('Gelli Haha',       '2025', '',           '',                                                0, 0, ''),
('Japanese Breakfast','2025','',           '',                                                0, 0, ''),
('The Kooks',        '2025', '',           '',                                                0, 0, ''),
('Mamalarky',        '2025', '',           '',                                                0, 0, ''),
('Mother Mother',    '2025', '',           '',                                                0, 0, ''),
('My Morning Jacket','2025', '',           '',                                                0, 0, ''),
('Nation of Language','2025','',           '',                                                0, 1, ''),
('Other Lives',      '2025', '',           '',                                                0, 0, ''),
('Patrick Watson',   '2025', '',           '',                                                0, 0, ''),
('Portugal. The Man','2025', '',           '',                                                0, 0, ''),
('Saint Motel',      '2025', '',           '',                                                0, 0, ''),
('Se So Neon',       '2025', '',           '',                                                0, 0, ''),
('Sleigh Bells',     '2025', '',           '',                                                0, 0, ''),
('Stella Donnelly',  '2025', '',           '',                                                0, 0, ''),
('Tame Impala',      '2025', '',           '',                                                0, 0, ''),
('The Voidz',        '2025', '',           '',                                                0, 0, ''),
('Warmland',         '2025', '',           '',                                                0, 0, ''),
('Wet Leg',          '2025', '',           '',                                                0, 0, ''),
('Whitney',          '2025', '',           '',                                                0, 0, ''),
('Angelo De Augustine','2026','',          '',                                                0, 0, ''),
('Arlo Parks',       '2026', '',           '',                                                0, 0, ''),
('The Dear Hunter',  '2026', '',           '',                                                0, 0, ''),
('Death Cab For Cutie','2026','',          '',                                                0, 0, ''),
('Gorillaz',         '2026', '',           '',                                                0, 0, ''),
('GUM',              '2026', '',           '',                                                0, 1, ''),
('The Hoosiers',     '2026', '',           '',                                                0, 0, ''),
('Miniature Tigers', '2026', '',           '',                                                0, 0, ''),
('Modest Mouse',     '2026', '',           '',                                                0, 0, ''),
('Paul McCartney',   '2026', '',           '',                                                0, 0, ''),
('Silversun Pickups','2026', '',           '',                                                0, 0, ''),
('Sure Sure',        '2026', '',           '',                                                0, 0, ''),
('underscores',      '2026', '',           '',                                                0, 0, '');
